import { createServer } from 'node:http';
import { WebSocketServer } from 'ws';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';

const PORT = process.env.PORT || 3000, MAX_PLAYERS = 20;
const rooms = new Map();
const animals = ['🐰','🦊','🐼','🐨','🐯','🐸','🐶','🐱','🐵','🦁','🐷','🦄','🐮','🐹','🐻','🐙','🦉','🐧','🐝','🦖'];
const code = () => Math.random().toString(36).slice(2,8).toUpperCase();
const json = (socket, payload) => socket && socket.readyState === socket.OPEN && socket.send(JSON.stringify(payload));
function view(room){return {phase:room.phase,countdown:room.countdown,chairCountdown:room.chairCountdown,players:[...room.players.values()].map(p=>({id:p.id,name:p.name,animal:p.animal,x:Math.round(p.x),y:Math.round(p.y),alive:p.alive})),chairs:room.chairs,bananas:room.bananas};}
function emit(room){for(const p of room.players.values())json(p.socket,{type:'state',state:view(room)});}
function makeRoom(){let id;do{id=code()}while(rooms.has(id));const room={id,host:null,players:new Map(),phase:'waiting',chairs:[],bananas:[],round:0,timer:null};rooms.set(id,room);return room;}
function add(room,socket,name){if(room.players.size>=MAX_PLAYERS)throw Error('방이 가득 찼습니다.');const id=Math.random().toString(36).slice(2);const p={id,room,socket,name:name.slice(0,10),animal:animals[room.players.size],x:480,y:320,alive:true,keys:{},cooldowns:{dash:0,push:0,banana:0},vx:0,vy:0};room.players.set(id,p);if(!room.host)room.host=id;socket.player=p;socket.room=room;json(socket,{type:'joined',id,room:room.id,host:room.host===id});emit(room);}
function addBot(room,name){const n=room.players.size;const p={id:`bot-${n}`,room,socket:null,name,animal:animals[n],x:480,y:320,alive:true,bot:true,keys:{},cooldowns:{},vx:0,vy:0,botAngle:n};room.players.set(p.id,p);}
function chairs(count){return Array.from({length:count},(_,i)=>{const a=(Math.PI*2*i/count)-Math.PI/2;return{x:Math.round(480+185*Math.cos(a)),y:Math.round(320+185*Math.sin(a))};});}
function start(room){if(room.phase!=='waiting'||room.players.size<1)return;if(room.players.size===1){addBot(room,'연습 여우');addBot(room,'연습 판다');}room.phase='countdown';room.countdown=3;emit(room);const timer=setInterval(()=>{room.countdown--;if(room.countdown===0){clearInterval(timer);beginRound(room);}else emit(room);},1000);}
function resetRoom(room){room.phase='waiting';room.round=0;room.chairs=[];room.bananas=[];room.countdown=null;for(const p of room.players.values()){p.alive=true;p.vx=p.vy=0;}emit(room);}
function beginRound(room){const alive=[...room.players.values()].filter(p=>p.alive);if(alive.length<=1)return finish(room);room.round++;room.phase='music';room.countdown=null;room.chairs=[];room.bananas=[{x:420,y:270},{x:550,y:350},{x:390,y:410}];alive.forEach((p,i)=>{const a=i*Math.PI*2/alive.length;p.x=480+230*Math.cos(a);p.y=320+230*Math.sin(a);p.vx=p.vy=0;});emit(room);setTimeout(()=>{if(room.phase!=='music')return;room.phase='chairs';room.chairs=chairs(alive.length-1);room.chairCountdown=8;emit(room);const timer=setInterval(()=>{room.chairCountdown--;if(room.chairCountdown===0){clearInterval(timer);resolve(room);}else if(room.phase==='chairs')emit(room);else clearInterval(timer);},1000);},10000+Math.random()*15000);}
function resolve(room){if(room.phase!=='chairs')return;const remaining=[...room.players.values()].filter(p=>p.alive);const seated=new Set();for(const chair of room.chairs){let winner=null,bestOverlap=0;for(const p of remaining){if(seated.has(p.id))continue;const overlap=Math.max(0,95-Math.hypot(p.x-chair.x,p.y-chair.y));if(overlap>bestOverlap){bestOverlap=overlap;winner=p;}}if(winner)seated.add(winner.id);}for(const p of remaining)if(!seated.has(p.id))p.alive=false;room.phase='result';room.chairCountdown=null;emit(room);setTimeout(()=>beginRound(room),2500);}
function finish(room){room.phase='finished';room.chairs=[];emit(room);}
function action(p,action){const now=Date.now();if(!p.alive||p.room?.phase==='waiting')return;if(now<(p.cooldowns[action]||0))return;if(action==='dash'){p.vx+=p.keys.right?520:p.keys.left?-520:0;p.vy+=p.keys.down?520:p.keys.up?-520:0;p.dashUntil=now+350;p.cooldowns.dash=now+600;}if(action==='push'){for(const other of p.room.players.values()){const dx=other.x-p.x,dy=other.y-p.y,d=Math.hypot(dx,dy);if(other!==p&&other.alive&&d<110){other.vx+=dx/d*2200;other.vy+=dy/d*2200;}}p.cooldowns.push=now+500;}if(action==='banana'){const speed=Math.hypot(p.vx,p.vy)||1;const x=Math.max(40,Math.min(920,p.x-p.vx/speed*52));const y=Math.max(40,Math.min(600,p.y-p.vy/speed*52));if(p.room.bananas.length<24)p.room.bananas.push({x,y,ownerId:p.id,armedUntil:now+900});p.cooldowns.banana=now+500;}}
setInterval(()=>{for(const room of rooms.values()){if(!['music','chairs'].includes(room.phase))continue;for(const p of room.players.values()){if(!p.alive)continue;const now=Date.now();let dx=(p.keys.right?1:0)-(p.keys.left?1:0),dy=(p.keys.down?1:0)-(p.keys.up?1:0);if(p.bot){const a=now/700+p.botAngle;dx=Math.cos(a);dy=Math.sin(a);}if(now>=(p.slipUntil||0)&&(dx||dy)){const l=Math.hypot(dx,dy);p.vx+=dx/l*150;p.vy+=dy/l*150;}for(let i=room.bananas.length-1;i>=0;i--){const b=room.bananas[i];if(b.ownerId===p.id&&now<b.armedUntil)continue;if(Math.hypot(p.x-b.x,p.y-b.y)<38){const speed=Math.hypot(p.vx,p.vy)||1;p.vx=p.vx/speed*330;p.vy=p.vy/speed*330;p.slipUntil=now+950;room.bananas.splice(i,1);}}const drag=now<(p.slipUntil||0)?.965:now<(p.dashUntil||0)?.9:.7;p.vx*=drag;p.vy*=drag;p.x=Math.max(40,Math.min(920,p.x+p.vx*.05));p.y=Math.max(40,Math.min(600,p.y+p.vy*.05));}emit(room);}},50);
setInterval(()=>{for(const room of rooms.values()){const now=Date.now(),players=[...room.players.values()].filter(p=>p.alive);for(let i=0;i<players.length;i++)for(let j=i+1;j<players.length;j++){const a=players[i],b=players[j];let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;if(d<108){dx/=d;dy/=d;if(now<(a.dashUntil||0)){b.vx+=dx*1500;b.vy+=dy*1500;a.dashUntil=0;}if(now<(b.dashUntil||0)){a.vx-=dx*1500;a.vy-=dy*1500;b.dashUntil=0;}const push=(108-d)/2;a.x=Math.max(54,Math.min(906,a.x-dx*push));a.y=Math.max(54,Math.min(586,a.y-dy*push));b.x=Math.max(54,Math.min(906,b.x+dx*push));b.y=Math.max(54,Math.min(586,b.y+dy*push));}}}},50);
const server=createServer(async(req,res)=>{try{let path=req.url==='/'?'/index.html':req.url;const file=await readFile(join(process.cwd(),'public',path));res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'application/javascript','.css':'text/css'}[extname(path)]||'application/octet-stream'});res.end(file);}catch{res.writeHead(404);res.end('Not found');}});
const wss=new WebSocketServer({server});wss.on('connection',socket=>socket.on('message',raw=>{try{const m=JSON.parse(raw);if(m.type==='create'){const room=makeRoom();add(room,socket,m.name||'동물');}else if(m.type==='join'){const room=rooms.get(m.code);if(!room||room.phase!=='waiting')throw Error('입장할 수 있는 방이 아닙니다.');add(room,socket,m.name||'동물');}else if(!socket.player)throw Error('먼저 방에 참가하세요.');else if(m.type==='start'||m.type==='restart'){if(socket.room.host!==socket.player.id)throw Error('방장만 시작할 수 있습니다.');if(m.type==='restart')resetRoom(socket.room);else start(socket.room);}else if(m.type==='key'){socket.player.keys[m.key]=Boolean(m.down);}else if(m.type==='action')action(socket.player,m.action);}catch(e){json(socket,{type:'error',message:e.message||'요청 처리에 실패했습니다.'});}}));
wss.on('connection',socket=>socket.on('close',()=>{const room=socket.room;if(!room)return;room.players.delete(socket.player.id);if(room.players.size===0)rooms.delete(room.id);else emit(room);}));server.listen(PORT,()=>console.log(`게임 서버: http://localhost:${PORT}`));
